package symphony.domain;

/**
 * This class represents a ticket.
 * It has a concert that is for, a price, and a unique ID
 * 
 * @author ???, updated by Adam Shalla
 *
 */
public class Ticket {

	/* CONSTRUCTORS	--------------------------------------------------	*/
	/**
	 * Initial Constructor
	 */
	public Ticket(){
		this(new Concert("blank concert"), 0.0d);
	}
	
	/**
	 * Parameterized Constrcutor
	 * 
	 * @param concert - The concert that the ticket is for
	 * @param ticketprice - The price of the ticket
	 */
	public Ticket(Concert concert, double ticketprice){
		this.ticketprice=ticketprice; 
		this.ticketID = UniqueID.getInstance();//this is autogenerated;s
		this.concert = concert;
	}

	/* ACCESSORS	--------------------------------------------------	*/
	/**
	 * @return The concert that the ticket is for
	 */
	public Concert getConcert() {
		return concert;
	}
	
	/**
	 * 
	 * @return The price of the ticket
	 */
	public double getTicketPrice(){
		return ticketprice; 
	}
	
	/**
	 * 
	 * @return The unique ID of the ticket
	 */
	public int getTicketID(){
		return ticketID; 
	}
	
	
	/* MODIFIERS	--------------------------------------------------	*/
	/**
	 * @param concert - The concert that the ticket is for
	 */
	public void setConcert(Concert concert) {
		this.concert = concert;
	}
	
	/**
	 * 
	 * @param ticketprice - The price of the ticket
	 */
	public void setTicketPrice(double ticketprice){
		this.ticketprice=ticketprice; 
	}
	
	/**
	 * @param ticketID - The unique ID of the ticket
	 */
	public void setTicketID(int ticketID) {
		this.ticketID = ticketID;
	}

	/**
	 * 
	 * @param ticketID - The unique ID of the ticket
	 */
	public void setTicketID(Integer ticketID){
		this.ticketID=ticketID; 
	}
	
	
	/* NORMAL BEHAVIOUR	----------------------------------------------	*/
	/**
	 * Displays the ticket information
	 */
	public void displayTicket(){
		System.out.println(concert);
		System.out.println("Ticket price: "+ ticketprice + " Ticket ID: "+ ticketID);
	}
	
	/* HELPER METHODS	----------------------------------------------	*/
	
	
	/* ATTRIBUTES	--------------------------------------------------	*/
	/**
	 * The concert that the ticket is for
	 */
	private Concert concert;
	
	/**
	 * The price of the ticket
	 */
	private double ticketprice;
	
	/**
	 * The unique ID of the ticket
	 */
	private int ticketID;
	
} /*	End of CLASS:	Ticket.java			*/	
	
	static class UniqueID{
		private static int uid = 0;
		public static int getInstance(){
			uid++;
			return uid;
		}
	}